### ISSUE TITLE
P2P-CR-11.12.21

### ISSUE THREAD

**Issue by OmarRamoun** [mrEckendonk/World-Energy-Event#2]
# 👋 Hello @Eckybrazzz 

## Suggested Improvements ♻️ 

- [x] ♻️ In the Partners Section, I believe it would be better if you change the color of the icons a little bit to  have a better look. You can use the function `filter: brightness(0) invert(0.7);`.
https://github.com/Eckybrazzz/World-Energy-Event/blob/38bf90a72dc381b40fe0a72f1b07836d6c36dd76/style.css#L419

**Comment by mrEckendonk** [comment]
Fixed and changed the color to a more white one.
Solution:
https://github.com/Eckybrazzz/World-Energy-Event/blob/a417d6855ad65c96dbc50225a2a4099341d642cf/style.css#L419
